### ISSUE TITLE
uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState (NameError) when running `mrsk init --bundle`

### ISSUE THREAD

**Issue by jasonfb** [mrsked/mrsk#174]
Getting `uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState (NameError)` when I try to setup MRSK on a Rails 7.0.2 / Ruby 3.1.1 app

```
% mrsk init --bundle
/Users/jason/.rvm/gems/ruby-3.1.1/gems/activesupport-7.0.2.2/lib/active_support/xml_mini.rb:184:in `current_thread_backend': uninitialized constant ActiveSupport::XmlMini::IsolatedExecutionState (NameError)

        IsolatedExecutionState[:xml_mini_backend]
        ^^^^^^^^^^^^^^^^^^^^^^
	from /Users/jason/.rvm/gems/ruby-3.1.1/gems/activesupport-7.0.2.2/lib/active_support/xml_mini.rb:103:in `backend='
	from /Users/jason/.rvm/gems/ruby-3.1.1/gems/activesupport-7.0.2.2/lib/active_support/xml_mini.rb:201:in `<module:ActiveSupport>'
	from /Users/jason/.rvm/gems/ruby-3.1.1/gems/activesupport-7.0.2.2/lib/active_support/xml_mini.rb:11:in `<top (required)>'
	from /Users/jason/.rvm/gems/ruby-3.1.1/gems/activesupport-7.0.2.2/lib/active_support/core_ext/array/conversions.rb:3:in `require'
	from /Users/jason/.rvm/gems/ruby-3.1.1/gems/activesupport-7.0.2.2/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
	from /Users/jason/.rvm/gems/ruby-3.1.1/gems/activesupport-7.0.2.2/lib/active_support/duration.rb:3:in `require'
	from /Users/jason/.rvm/gems/ruby-3.1.1/gems/activesupport-7.0.2.2/lib/active_support/duration.rb:3:in `<top (required)>'
	from /Users/jason/.rvm/gems/ruby-3.1.1/gems/mrsk-0.3.1/lib/mrsk/commands/prune.rb:2:in `require'
	from /Users/jason/.rvm/gems/ruby-3.1.1/gems/mrsk-0.3.1/lib/mrsk/commands/prune.rb:2:in `<top (required)>'
	from /Users/jason/.rvm/gems/ruby-3.1.1/gems/mrsk-0.3.1/lib/mrsk/commander.rb:7:in `require'
	from /Users/jason/.rvm/gems/ruby-3.1.1/gems/mrsk-0.3.1/lib/mrsk/commander.rb:7:in `<top (required)>'
	from /Users/jason/.rvm/gems/ruby-3.1.1/gems/mrsk-0.3.1/lib/mrsk.rb:5:in `require'
	from /Users/jason/.rvm/gems/ruby-3.1.1/gems/mrsk-0.3.1/lib/mrsk.rb:5:in `<top (required)>'
	from /Users/jason/.rvm/gems/ruby-3.1.1/gems/mrsk-0.3.1/lib/mrsk/cli.rb:1:in `require'
	from /Users/jason/.rvm/gems/ruby-3.1.1/gems/mrsk-0.3.1/lib/mrsk/cli.rb:1:in `<top (required)>'
	from /Users/jason/.rvm/gems/ruby-3.1.1/gems/mrsk-0.3.1/bin/mrsk:6:in `require'
	from /Users/jason/.rvm/gems/ruby-3.1.1/gems/mrsk-0.3.1/bin/mrsk:6:in `<top (required)>'
	from /Users/jason/.rvm/gems/ruby-3.1.1/bin/mrsk:25:in `load'
	from /Users/jason/.rvm/gems/ruby-3.1.1/bin/mrsk:25:in `<main>'
	from /Users/jason/.rvm/gems/ruby-3.1.1/bin/ruby_executable_hooks:22:in `eval'
	from /Users/jason/.rvm/gems/ruby-3.1.1/bin/ruby_executable_hooks:22:in `<main>'

```

Gemfile
```
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.1"
gem "rails", "~> 7.0.2"
gem "sprockets-rails"
gem "pg", "~> 1.1"
gem "puma"
gem "jsbundling-rails"
gem "cssbundling-rails"
gem "sassc-rails"
gem "turbo-rails"
gem "stimulus-rails"

gem "jbuilder"
gem "redis", "~> 4.0"

gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem "bootsnap", require: false
group :development, :test do
  gem 'ffaker'
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'dotenv-rails'
  gem 'rspec-rails'
  gem 'rspec-wait'
  gem 'vcr'
  gem 'factory_bot_rails', require: true
  gem "factory_bot", require: true
  gem 'simplecov'
  gem 'bullet'
end

gem 'hot-glue'

group :development do
  gem "web-console"
end

gem 'rspec_junit_formatter'

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end

gem "mrsk", "~> 0.3.1"
```

**Comment by jasonfb** [comment]
this is very odd the problem seems to have gone away without explanation

**Comment by jasonfb** [comment]
I have no isolated it and I suspect it had something to do with the Gem versions, but it oddly comes and goes without explanation

**Comment by jasonfb** [comment]
this could have been a fluke because it seemed to have just gone away without explanation. will reopen if I find more info

**Comment by jasonfb** [comment]
I think this was due to a very old version of mrsk
