### ISSUE TITLE
`hotwire-rails` breaks deployment (health check)

### ISSUE THREAD

**Issue by janschill** [mrsked/mrsk#243]
I've noticed that as soon as I install `hotwire-rails` in my Rails application the deployment fails at the health check stage.

<details><summary>Stack Trace of Failure</summary>
<p>

```sh
  INFO [6eae2c7a] Finished in 9.747 seconds with exit status 0 (successful).
  INFO [4de8d5bc] Running docker image rm --force janschill/29:4fd4245818896e755430cd5833727f3b16f633fe on ***.***.***.***
  INFO [4de8d5bc] Finished in 0.149 seconds with exit status 0 (successful).
  INFO [99c4bd09] Running docker pull janschill/29:latest on ***.***.***.***
  INFO [99c4bd09] Finished in 1.661 seconds with exit status 0 (successful).
Ensure Traefik is running...
  INFO [cd1c2705] Running docker login -u [REDACTED] -p [REDACTED] on ***.***.***.***
  INFO [cd1c2705] Finished in 1.125 seconds with exit status 0 (successful).
  INFO [89d684e9] Running docker run --name traefik --detach --restart unless-stopped --publish 80:80 --volume /var/run/docker.sock:/var/run/docker.sock --log-opt max-size="10m" traefik:v2.9 --providers.docker --log.level=DEBUG on ***.***.***.***
  INFO [89d684e9] Finished in 0.150 seconds with exit status 125 (failed).
Ensure app can pass healthcheck...
  INFO [15732d2a] Running docker run --detach --name healthcheck-twni-4fd4245818896e755430cd5833727f3b16f633fe --publish 3999:3000 --label service=healthcheck-twni -e MRSK_CONTAINER_NAME="healthcheck-twni" -e [REDACTED] janschill/29:4fd4245818896e755430cd5833727f3b16f633fe on ***.***.***.***
  INFO [15732d2a] Finished in 1.756 seconds with exit status 0 (successful).
  INFO [35cbbd57] Running /usr/bin/env curl --silent --output /dev/null --write-out '%{http_code}' --max-time 2 http://localhost:3999/up on ***.***.***.***
  INFO Health check against /up failed to respond, retrying in 1s (attempt 1/7)...
  INFO [8c5ec04c] Running /usr/bin/env curl --silent --output /dev/null --write-out '%{http_code}' --max-time 2 http://localhost:3999/up on ***.***.***.***
  INFO Health check against /up failed to respond, retrying in 2s (attempt 2/7)...
  INFO [8884805c] Running /usr/bin/env curl --silent --output /dev/null --write-out '%{http_code}' --max-time 2 http://localhost:3999/up on ***.***.***.***
  INFO Health check against /up failed to respond, retrying in 3s (attempt 3/7)...
  INFO [fc311daf] Running /usr/bin/env curl --silent --output /dev/null --write-out '%{http_code}' --max-time 2 http://localhost:3999/up on ***.***.***.***
  INFO Health check against /up failed to respond, retrying in 4s (attempt 4/7)...
  INFO [7fad7859] Running /usr/bin/env curl --silent --output /dev/null --write-out '%{http_code}' --max-time 2 http://localhost:3999/up on ***.***.***.***
  INFO Health check against /up failed to respond, retrying in 5s (attempt 5/7)...
  INFO [2a3b7c47] Running /usr/bin/env curl --silent --output /dev/null --write-out '%{http_code}' --max-time 2 http://localhost:3999/up on ***.***.***.***
  INFO Health check against /up failed to respond, retrying in 6s (attempt 6/7)...
  INFO [edcc9d5e] Running /usr/bin/env curl --silent --output /dev/null --write-out '%{http_code}' --max-time 2 http://localhost:3999/up on ***.***.***.***
  INFO Health check against /up failed to respond, retrying in 7s (attempt 7/7)...
  INFO [b2075c40] Running /usr/bin/env curl --silent --output /dev/null --write-out '%{http_code}' --max-time 2 http://localhost:3999/up on ***.***.***.***
  INFO [f2d12f71] Running docker container ls --all --filter name=^healthcheck-twni-4fd4245818896e755430cd5833727f3b16f633fe$ --quiet | xargs docker logs --tail 50 2>&1 on ***.***.***.***
  INFO [f2d12f71] Finished in 0.216 seconds with exit status 0 (successful).
 ERROR from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:16:in `each'
	from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
	from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
	from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
	from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader.rb:297:in `block in eager_load_all'
	from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader.rb:295:in `each'
	from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader.rb:295:in `eager_load_all'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-d8a8df3d854a/railties/lib/rails/application/finisher.rb:80:in `block in <module:Finisher>'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-d8a8df3d854a/railties/lib/rails/initializable.rb:32:in `instance_exec'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-d8a8df3d854a/railties/lib/rails/initializable.rb:32:in `run'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-d8a8df3d854a/railties/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `call'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-d8a8df3d854a/railties/lib/rails/initializable.rb:60:in `run_initializers'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-d8a8df3d854a/railties/lib/rails/application.rb:420:in `initialize!'
	from /rails/config/environment.rb:5:in `<top (required)>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /usr/local/bundle/ruby/3.2.0/gems/rack-3.0.7/lib/rack/builder.rb:103:in `eval'
	from /usr/local/bundle/ruby/3.2.0/gems/rack-3.0.7/lib/rack/builder.rb:103:in `new_from_string'
	from /usr/local/bundle/ruby/3.2.0/gems/rack-3.0.7/lib/rack/builder.rb:94:in `load_file'
	from /usr/local/bundle/ruby/3.2.0/gems/rack-3.0.7/lib/rack/builder.rb:64:in `parse_file'
	from /usr/local/bundle/ruby/3.2.0/gems/rackup-2.1.0/lib/rackup/server.rb:354:in `build_app_and_options_from_config'
	from /usr/local/bundle/ruby/3.2.0/gems/rackup-2.1.0/lib/rackup/server.rb:263:in `app'
	from /usr/local/bundle/ruby/3.2.0/gems/rackup-2.1.0/lib/rackup/server.rb:424:in `wrapped_app'
	from /usr/local/bundle/ruby/3.2.0/gems/rackup-2.1.0/lib/rackup/server.rb:326:in `block in start'
	from /usr/local/bundle/ruby/3.2.0/gems/rackup-2.1.0/lib/rackup/server.rb:382:in `handle_profiling'
	from /usr/local/bundle/ruby/3.2.0/gems/rackup-2.1.0/lib/rackup/server.rb:325:in `start'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-d8a8df3d854a/railties/lib/rails/commands/server/server_command.rb:39:in `start'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-d8a8df3d854a/railties/lib/rails/commands/server/server_command.rb:145:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-d8a8df3d854a/railties/lib/rails/commands/server/server_command.rb:136:in `perform'
	from /usr/local/bundle/ruby/3.2.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/ruby/3.2.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-d8a8df3d854a/railties/lib/rails/command/base.rb:179:in `invoke_command'
	from /usr/local/bundle/ruby/3.2.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-d8a8df3d854a/railties/lib/rails/command/base.rb:74:in `perform'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-d8a8df3d854a/railties/lib/rails/command.rb:71:in `block in invoke'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-d8a8df3d854a/railties/lib/rails/command.rb:149:in `with_argv'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-d8a8df3d854a/railties/lib/rails/command.rb:69:in `invoke'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-d8a8df3d854a/railties/lib/rails/commands.rb:18:in `<top (required)>'
	from /rails/bin/rails:4:in `require'
	from /rails/bin/rails:4:in `<main>'
  INFO [0f0ccc62] Running docker container ls --all --filter name=^healthcheck-twni-4fd4245818896e755430cd5833727f3b16f633fe$ --quiet | xargs docker stop on ***.***.***.***
  INFO [0f0ccc62] Finished in 0.182 seconds with exit status 0 (successful).
  INFO [bf0ba45e] Running docker container ls --all --filter name=^healthcheck-twni-4fd4245818896e755430cd5833727f3b16f633fe$ --quiet | xargs docker container rm on ***.***.***.***
  INFO [bf0ba45e] Finished in 0.194 seconds with exit status 0 (successful).
  Finished all in 47.3 seconds
  Deploy lock was not released
  ERROR (SSHKit::Command::Failed): Health check against /up failed to return 200 OK!
```

</p>
</details> 

Note the lines

```sh
  INFO [89d684e9] Running docker run --name traefik --detach --restart unless-stopped --publish 80:80 --volume /var/run/docker.sock:/var/run/docker.sock --log-opt max-size="10m" traefik:v2.9 --providers.docker --log.level=DEBUG on 167.172.103.224
  INFO [89d684e9] Finished in 0.150 seconds with exit status 125 (failed).
```

The logs for Traefik do not really report anything meaningful at the time of failure. I had noticed a `exit status 125 (failed) previously without a subsequent issue on the health check. I have no additional configuration for Traefik in my `deploy.yml`

```yml
service: twni
image: janschill/29
servers:
  - ******
registry:
  username: ******
  password:
    - MRSK_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY
```

**Comment by janschill** [comment]
Found more information

```
root@server:~# docker logs 7f59a8c2f3fa -f
W, [2023-04-25T17:09:49.351632 #7]  WARN -- : You are running SQLite in production, this is generally not recommended. You can disable this warning by setting "config.active_record.sqlite3_production_warning=false".
=> Booting Puma
=> Rails 7.1.0.alpha application starting in production http://0.0.0.0:3000
=> Run `bin/rails server --help` for more startup options
/usr/local/bundle/ruby/3.2.0/gems/rack-3.0.7/lib/rack/chunked.rb:6: warning: Rack::Chunked is deprecated and will be removed in Rack 3.1
W, [2023-04-25T17:09:53.358613 #1]  WARN -- : You are running SQLite in production, this is generally not recommended. You can disable this warning by setting "config.active_record.sqlite3_production_warning=false".
Exiting
/usr/local/bundle/ruby/3.2.0/gems/turbo-rails-1.4.0/app/jobs/turbo/streams/action_broadcast_job.rb:2:in `<top (required)>': uninitialized constant ActiveJob (NameError)

class Turbo::Streams::ActionBroadcastJob < ActiveJob::Base
                                                    ^^^^^^
Did you mean?  ActiveModel
	from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:30:in `require'
	from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:30:in `require'
	from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
	from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:135:in `cget'
	from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:169:in `block in actual_eager_load_dir'
	from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
	from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:25:in `each'
	from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:25:in `ls'
	from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:164:in `actual_eager_load_dir'
	from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
	from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:16:in `each'
	from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
	from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
	from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
	from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader.rb:297:in `block in eager_load_all'
	from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader.rb:295:in `each'
	from /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader.rb:295:in `eager_load_all'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-744b6715a5d0/railties/lib/rails/application/finisher.rb:80:in `block in <module:Finisher>'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-744b6715a5d0/railties/lib/rails/initializable.rb:32:in `instance_exec'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-744b6715a5d0/railties/lib/rails/initializable.rb:32:in `run'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-744b6715a5d0/railties/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `call'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
	from /usr/local/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-744b6715a5d0/railties/lib/rails/initializable.rb:60:in `run_initializers'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-744b6715a5d0/railties/lib/rails/application.rb:420:in `initialize!'
	from /rails/config/environment.rb:5:in `<top (required)>'
	from config.ru:3:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /usr/local/bundle/ruby/3.2.0/gems/rack-3.0.7/lib/rack/builder.rb:103:in `eval'
	from /usr/local/bundle/ruby/3.2.0/gems/rack-3.0.7/lib/rack/builder.rb:103:in `new_from_string'
	from /usr/local/bundle/ruby/3.2.0/gems/rack-3.0.7/lib/rack/builder.rb:94:in `load_file'
	from /usr/local/bundle/ruby/3.2.0/gems/rack-3.0.7/lib/rack/builder.rb:64:in `parse_file'
	from /usr/local/bundle/ruby/3.2.0/gems/rackup-2.1.0/lib/rackup/server.rb:354:in `build_app_and_options_from_config'
	from /usr/local/bundle/ruby/3.2.0/gems/rackup-2.1.0/lib/rackup/server.rb:263:in `app'
	from /usr/local/bundle/ruby/3.2.0/gems/rackup-2.1.0/lib/rackup/server.rb:424:in `wrapped_app'
	from /usr/local/bundle/ruby/3.2.0/gems/rackup-2.1.0/lib/rackup/server.rb:326:in `block in start'
	from /usr/local/bundle/ruby/3.2.0/gems/rackup-2.1.0/lib/rackup/server.rb:382:in `handle_profiling'
	from /usr/local/bundle/ruby/3.2.0/gems/rackup-2.1.0/lib/rackup/server.rb:325:in `start'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-744b6715a5d0/railties/lib/rails/commands/server/server_command.rb:39:in `start'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-744b6715a5d0/railties/lib/rails/commands/server/server_command.rb:145:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-744b6715a5d0/railties/lib/rails/commands/server/server_command.rb:136:in `perform'
	from /usr/local/bundle/ruby/3.2.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/ruby/3.2.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-744b6715a5d0/railties/lib/rails/command/base.rb:179:in `invoke_command'
	from /usr/local/bundle/ruby/3.2.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-744b6715a5d0/railties/lib/rails/command/base.rb:74:in `perform'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-744b6715a5d0/railties/lib/rails/command.rb:71:in `block in invoke'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-744b6715a5d0/railties/lib/rails/command.rb:149:in `with_argv'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-744b6715a5d0/railties/lib/rails/command.rb:69:in `invoke'
	from /usr/local/bundle/ruby/3.2.0/bundler/gems/rails-744b6715a5d0/railties/lib/rails/commands.rb:18:in `<top (required)>'
	from /rails/bin/rails:4:in `require'
	from /rails/bin/rails:4:in `<main>'
```
